cors:
  allowed-origins: "http://localhost:5173"

spring:
  datasource:
    url: jdbc:h2:mem:tradingdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

# Configuration Discord
discord:
  webhook-url: ${DISCORD_WEBHOOK_URL}

# Configuration Actuator (Monitoring / Metrics)
management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health, info"

# Configuration AI API
ai:
  api:
    url: "http://localhost:9078"
