package fr.info803.trading_assistant.controller;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Collections;
import java.util.List;

import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import fr.info803.trading_assistant.dto.AssetSummaryResponse;
import fr.info803.trading_assistant.dto.CandleResponse;
import fr.info803.trading_assistant.exception.AssetNotFoundException;
import fr.info803.trading_assistant.exception.GlobalExceptionHandler;
import fr.info803.trading_assistant.service.AssetService;

/**
 * Unit tests for AssetController.
 *
 * Uses MockMvcBuilders.standaloneSetup() — no Spring context, no security infrastructure.
 * Only AssetController and GlobalExceptionHandler are registered. AssetService is mocked.
 *
 * Why standaloneSetup() and not @WebMvcTest?
 *   @WebMvcTest loads SecurityConfig → ApplicationConfig → AccountRepository (a @Repository
 *   not available in a web slice). standaloneSetup() avoids this coupling entirely by building
 *   MockMvc manually with only the components under test.
 *
 * Date field assertions use .exists() rather than exact string values because date serialization
 * format (ISO-8601 vs array) depends on the runtime Jackson configuration, which is Spring
 * Boot's autoconfiguration responsibility, not the controller's.
 *
 * Covers:
 * - GET /assets: 200 with asset list (symbol, lastPrice, lastDate), 200 with empty array
 * - GET /assets/{symbol}/candles: 200 with OHLCV candles, 200 with empty array,
 *   404 with error JSON via GlobalExceptionHandler when asset is unknown
 */
@DisplayName("AssetController Unit Tests")
@ExtendWith(MockitoExtension.class)
class AssetControllerTest {

    private MockMvc mockMvc;

    @Mock
    private AssetService assetService;

    @BeforeEach
    void setUp() {
        /*
            standaloneSetup registers only the controller and the exception handler.
            No security, no application context, no repository beans needed.
            AssetController uses @RequiredArgsConstructor — constructor generated by Lombok.
        */
        mockMvc = MockMvcBuilders
            .standaloneSetup(new AssetController(assetService))
            .setControllerAdvice(new GlobalExceptionHandler())
            .build();
    }

    // =========================================================================
    // GET /assets
    // =========================================================================

    @Nested
    @DisplayName("GET /assets")
    class GetAssetsTests {

        @Test
        @DisplayName("should return 200 with list of asset summaries")
        void shouldReturn200WithListOfAssets() throws Exception {
            // Arrange
            List<AssetSummaryResponse> summaries = List.of(
                AssetSummaryResponse.builder()
                    .symbol("BTC")
                    .lastPrice(new BigDecimal("96000.50"))
                    .lastDate(LocalDate.of(2026, 2, 27))
                    .build(),
                AssetSummaryResponse.builder()
                    .symbol("ETH")
                    .lastPrice(new BigDecimal("3150.25"))
                    .lastDate(LocalDate.of(2026, 2, 27))
                    .build()
            );
            when(assetService.getAssetSummaries()).thenReturn(summaries);

            // Act & Assert
            mockMvc.perform(get("/assets"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].symbol").value("BTC"))
                .andExpect(jsonPath("$[0].lastPrice").isNumber())
                .andExpect(jsonPath("$[0].lastDate").exists())   // format delegated to Spring Boot autoconfiguration
                .andExpect(jsonPath("$[1].symbol").value("ETH"))
                .andExpect(jsonPath("$[1].lastPrice").isNumber())
                .andExpect(jsonPath("$[1].lastDate").exists());
        }

        @Test
        @DisplayName("should return 200 with empty array when no assets exist")
        void shouldReturn200WithEmptyList() throws Exception {
            // Arrange
            when(assetService.getAssetSummaries()).thenReturn(Collections.emptyList());

            // Act & Assert: empty list must return 200, not 204
            mockMvc.perform(get("/assets"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$").isEmpty());
        }
    }

    // =========================================================================
    // GET /assets/{symbol}/candles
    // =========================================================================

    @Nested
    @DisplayName("GET /assets/{symbol}/candles")
    class GetCandlesTests {

        @Test
        @DisplayName("should return 200 with candles for known symbol")
        void shouldReturn200WithCandles() throws Exception {
            // Arrange
            List<CandleResponse> candles = List.of(
                CandleResponse.builder()
                    .date(LocalDate.of(2026, 1, 15))
                    .open(new BigDecimal("95000"))
                    .high(new BigDecimal("96500"))
                    .low(new BigDecimal("94000"))
                    .close(new BigDecimal("96000"))
                    .volume(new BigDecimal("1234.5"))
                    .build()
            );
            when(assetService.getCandles("BTC")).thenReturn(candles);

            // Act & Assert
            mockMvc.perform(get("/assets/BTC/candles"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$.length()").value(1))
                .andExpect(jsonPath("$[0].date").exists())
                .andExpect(jsonPath("$[0].open").isNumber())
                .andExpect(jsonPath("$[0].high").isNumber())
                .andExpect(jsonPath("$[0].low").isNumber())
                .andExpect(jsonPath("$[0].close").isNumber())
                .andExpect(jsonPath("$[0].volume").isNumber());
        }

        @Test
        @DisplayName("should return 200 with empty array when no candles exist in the period")
        void shouldReturn200WithEmptyListWhenNoCandlesInPeriod() throws Exception {
            // Arrange
            when(assetService.getCandles("BTC")).thenReturn(Collections.emptyList());

            // Act & Assert
            mockMvc.perform(get("/assets/BTC/candles"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$").isEmpty());
        }

        @Test
        @DisplayName("should return 404 with error JSON when asset is not found (GlobalExceptionHandler)")
        void shouldReturn404WithErrorJsonWhenAssetNotFound() throws Exception {
            // Arrange: service throws AssetNotFoundException → GlobalExceptionHandler maps it to 404
            when(assetService.getCandles("UNKNOWN")).thenThrow(new AssetNotFoundException("UNKNOWN"));

            // Act & Assert
            mockMvc.perform(get("/assets/UNKNOWN/candles"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error").value("Asset not found"))
                .andExpect(jsonPath("$.symbol").value("UNKNOWN"))
                .andExpect(jsonPath("$.timestamp").exists());
        }
    }
}
